### ISSUE TITLE
Support for SLES 11/12

### ISSUE THREAD

**Issue by Cryun** [Azure/azure-storage-fuse#189]
Hi there,

I was wondering whether or not Blobfuse in Azure is supported on SLES? I couldn't find any guide or instruction on how to install it on SLES.

Thanks in advance!

**Comment by seguler** [comment]
Here are the steps that were shared by another user here:

```zypper install git cmake3 fuse-devel libcurl-devel gcc gcc-c++ gnutls-devel libgcrypt-devel fuse
git clone https://github.com/Azure/azure-storage-fuse/
cd /azure-storage-fuse/
./build.sh```

Could you test and let us know if it works ?

**Comment by mxkss** [comment]
Dear segular,

i try to install some packages as your suggestion on SLES 12 SP3 & then run build.sh
I got error as below,

![image](https://user-images.githubusercontent.com/42959964/45017231-48802f80-b051-11e8-9482-ada38ec724ce.png)

Please kindly help or you've another ways.

**Comment by ernani** [comment]
try also installing libcurl4-openssl-dev, that should fix it.

**Comment by AGLbwa** [comment]
Update to those steps:
zypper install git cmake fuse-devel libcurl-devel gcc gcc-c++ gnutls-devel libgcrypt-devel fuse libuuid-devel

(This did the trick for me.)

**Comment by hiranyakpeiris** [comment]
I syned my repo with SCC(SLES repo)
Still cannot find the following packages:
Package 'fuse-devel' not found.
No provider of 'git' found.
No provider of 'libuuid-devel' found.
No provider of 'libgcrypt-devel' found.
No provider of 'libcurl-devel' found.

**Comment by hiranyakpeiris** [comment]
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindCURL.cmake:61 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:124 (find_package)


-- Configuring incomplete, errors occurred!
See also "/opt/rpm/azure-storage-fuse/build/CMakeFiles/CMakeOutput.log".
See also "/opt/rpm/azure-storage-fuse/build/CMakeFiles/CMakeError.log".
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindCURL.cmake:61 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:124 (find_package)


-- Configuring incomplete, errors occurred!
See also "/opt/rpm/azure-storage-fuse/build/CMakeFiles/CMakeOutput.log".
See also "/opt/rpm/azure-storage-fuse/build/CMakeFiles/CMakeError.log".
cmake failed.  Please ensure that cmake version 3.5 or greater is installed and available.

cmake version is 3.5.2
